Project3:Pizza/first_project/first_app/urls.py
from django.conf.urls import url
from first_app import views
from django.urls import path
#template tagging

app_name = 'first_app'

urlpatterns = [
    url(r'^cart/',views.cart,name='cart'),
    #url(r'^$', views.form_name_view, name='form_name'),  #is line ka matlab hai jab 127.0.0.1:8000 ho tab index.html call ko index function sa view.py ma
    #url(r'^signup/', views.signup, name='signup'),
    #url(r'^menu/',views.menu,name = 'menu'),
    #url(r'^welcome/',views.welcome,name = 'welcome'),
    #url(r'^logout/', views.logout, name='logout'),
#    url('r^admin/',views.admin,name='admin')
]
#/home/shashank/gitprac/CS50edx/lecture7/project3/first_project/first_app/urls.py

Project3:Pizza/first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path
from first_app import views
from django.conf.urls import url,include

""" url(r'^cart/',include('first_app.urls')),
    url(r'^logout/',include('first_app.urls')),
    url(r'^$',views.form_name_view,name='form_name'),
    url(r'^signup/',include('first_app.urls')),
    url(r'^menu/',include('first_app.urls')),
    url(r'^welcome/',include('first_app.urls')),
"""

urlpatterns = [
    url(r'first_app/',include('first_app.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^cart/',views.cart,name='cart'),
    url(r'^$', views.form_name_view, name='form_name'),  #is line ka matlab hai jab 127.0.0.1:8000 ho tab index.html call ko index function sa view.py ma
    url(r'^signup/', views.signup, name='signup'),
    url(r'^menu/',views.menu,name = 'menu'),
    url(r'^welcome/',views.welcome,name = 'welcome'),
    url(r'^logout/', views.logout, name='logout'),
    #path('signup/',include('first_app.urls')),  #is line ka matlab hai jab 127.0.0.1:8000/sigup/ ho tab signup function call ko view.py sa iski mapping urls.py ma hui hai jo ki first_app hai.
    #path('formpage/',views.form_name_view,name = 'form_name'),
]
#/home/shashank/gitprac/CS50edx/lecture7/project3/first_project/first_project/urls.py

Project3:Pizza/first_project/first_app/models.py
from django.db import models
from django import forms
# Create your models here.
class Users(models.Model):

    username = models.CharField(max_length=50)
    email = models.EmailField()
    password = models.CharField(max_length=50)
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)

    def __str__(self):
        return self.username

class category(models.Model):
        catid = models.IntegerField()
        catname = models.CharField(max_length=50)

        def __str__(self):
            return self.catname

class pizzaselection(models.Model):
        pid = models.IntegerField()
        catid = models.ForeignKey(category,on_delete = models.CASCADE)
        pname = models.CharField(max_length=50)
        psize = models.CharField(max_length=100)
        pprice = models.FloatField()
        tname = models.CharField(max_length=50) # topping name

        def __str__(self):
            return self.pid

Project3:Pizza/first_project/first_app/forms.py
from django import forms
from first_app.models import Users
from django.core import validators

class NewUserform(forms.ModelForm):
    class Meta:
        model = Users
        fields = '__all__'

class loginname(forms.Form):

        Username = forms.CharField(max_length=50)
        password = forms.CharField(widget=forms.PasswordInput)

        verify_password = forms.CharField(label='Retype Password',widget=forms.PasswordInput)

        #botcatcher = forms.CharField(required = False,widget = forms.HiddenInput,validators=[validators.MaxLengthValidator(0)])


        def clean(self):
            all_clean_data = super().clean()
            password = all_clean_data['password']
            vpassword = all_clean_data['verify_password']

            if password != vpassword :
               raise forms.validationError("Make Sure Password Matches!")


        #def clean_botcatcher(self):
        #    botcatcher = self.cleaned_data['botcatcher']
        #    if len(botcatcher) > 0:
        #        raise forms.validationError("Nothing Can be done so don't try to hack XD:)!")
        #    return botcatcher

Project3:Pizza/first_project/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import forms # . means the current dircetory
from first_app.forms import NewUserform
# Create your views here.

def form_name_view(request):
    form = forms.loginname()
    return render(request,'first_app/index.html',{'form':form})

def cart(request):
    from first_app.models import Users,category,pizzaselection
    #pizzamenu = pizzaselection.objects.order_by('pid')
    #pizzavalue = request.POST.get('1')
    #pizzamenu = pizzaselection.objects.values('pid')
    #for pizzai in pizzamenu:
    #        if pizzai == '1':
                #finalval = pizzaselection.objects.values('pizzavalue')
    #            pizzalist = {'pizza_selection':pizzamenu}
    #return render(request,'first_app/cart.html')#,context=pizzalist)
    return HttpResponse("Successfully ordered placed.")

def logout(request):
    return render(request,'first_app/index.html')

def welcome(request):
    form = forms.loginname()
    return render(request,'first_app/welcome.html')

def menu(request):
    from first_app.models import Users,category,pizzaselection
    pizzamenu = pizzaselection.objects.order_by('pid')
    pizzalist = {'pizza_selection':pizzamenu}
    return render(request,'first_app/menu.html',context=pizzalist)

def signup(request):

    registered = False
    form = NewUserform()

    if request.method == "POST":

        form = NewUserform(request.POST)

        if form.is_valid():
            form.save(commit=True)
            registered = True
            render(request,'first_app/form_name_view')
        else:
            print("Error Form Invalid Check Your Id and Password")

    return render(request,'first_app/signup.html',{'form':form,'registered':registered})

Project3:Pizza/templates/first_app/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Pizza Mania</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
    	<link rel="stylesheet" href="../static/css/p0style.css">
      <link rel="stylesheet" href="../static/css/style.css">
    	<link rel="stylesheet" href="../static/css/styling.css">
    	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  </head>
  <header class="head">
	<h1 class="container">Welcome to Pizza Mania</h1>
	<h3  class="container" style="text-align:right">Know Pizza Mania on :</h3>
	<a href="https://www.facebook.com/profile.php?id=100011328984158&ref=bookmarks" target="_blank"><img src="../static/images/fb" alt="facebook" height="50" width="50" style="float:right"></a>
</header>

<nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">

          {# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:register' %}">Register</a></li>

          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'basic_app:user_login' %}">Login</a></li>
          {% endif %}

        </ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>


  </body>
</html>

Project3:Pizza/templates/first_app/cart.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Pizza Mania</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="../static/css/p0style.css">
    <link rel="stylesheet" href="../static/css/style.css">
    <link rel="stylesheet" href="../static/css/styling.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  </head>
  <header class="head">
  <h1 class="container">Just One step Away to have a delicious Pizza</h1>
</header>
<body id="indexbody">
  <br><br>
  <div id="welcome">
    <h3>Order selected:</h2>
      {% if pizza_selection %}
        <table id="customers" align="center">
          <t/head>
            <th>Sno.:</th>
            <th>Category:</th>
            <th>PizzaName:&nbsp;</th>
            <th>Size:</th>
            <th>Price:</th>
            <th>Topping:</th>
          </thead>


      {% for acc in pizza_selection %}
      <tr>
          <td>&nbsp;&nbsp;{{acc.pid}}&nbsp;&nbsp;</td>
          <td>&nbsp;&nbsp;{{acc.catid}}&nbsp;&nbsp;</td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{acc.pname}}&nbsp;&nbsp;</td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;{{acc.psize}}&nbsp;&nbsp;</td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;{{acc.pprice}}&nbsp;&nbsp;</td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;{{acc.tname}}&nbsp;&nbsp;</td>
        </tr>
      {% endfor %}
    </table>
    {% else %}
    <p>Nothing in Cart</p>
    {% endif %}
</div>
  </div>
</body>
  </html>

Project3:Pizza/templates/first_app/index.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Pizza Mania</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
    	<link rel="stylesheet" href="../static/css/p0style.css">
      <link rel="stylesheet" href="../static/css/style.css">
    	<link rel="stylesheet" href="../static/css/styling.css">
    	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  </head>
  <header class="head">
	<h1 class="container">Welcome to Pizza Mania</h1>
  <a href='http://127.0.0.1:8000/admin/'><button type="button" class="btn btn-light" style="float: right;">Admin</button></a>
</header>
<body id="indexbody">
  <br><br>
  	<b><h1 class="container" style="text-align:left">Login as User</h1></b>
      <!--<form class="container" action="redirect(/'welcome/')" method="post" autocomplete="off"><br>
  	          <h5 class="forbold">User Name:</h5>
              <input type="name" name=name placeholder="Login name" autofocus/><br>
  	          <h5 class="forbold">Password:</h5>
  	          <input type="Password" name=pass placeholder="Password" autofocus/>
<br><br>
              <input type=Submit value="Submit"> &nbsp;
    	       <a href="redirect(/'signup/')"><button type="button" class="btn btn-light">Sign Up</button></a>-->
             <div class="container">
               <form class="container" action='http://127.0.0.1:8000/welcome/' method="POST" autocomplete="off">
                   {{ form.as_p }}
                   <br>
                   <input type="submit" class="btn btn-primary" value="Submit">&nbsp; &nbsp; &nbsp;&nbsp;
                   <a href='http://127.0.0.1:8000/signup/'><button type="button" class="btn btn-light">Sign Up</button></a>
                 </form>
            </div>
</body>
<footer class="foot">
	<h3 class="container">Get the code on Github</h3>
  <a href="https://github.com/tshashankrock/CS50edx/tree/master/project0" target="_blank"><img  id="imgtag" src="../static/images/gitimg" alt="github" height="50" width="50"></a>
</footer>
</html>

Project3:Pizza/templates/first_app/layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
    	<link rel="stylesheet" href="../static/p0style.css">
      <link rel="stylesheet" href="../static/style.css">
    	<link rel="stylesheet" href="../static/styling.css">
    	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  </head>
  {% block content %}
  {% endblock %}
</html>

Project3:Pizza/templates/first_app/menu.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <style>
    font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
    border-collapse: collapse;
    #customers {
    }

    #customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
  }
  #customers tr:hover {background-color: #ddd;}
  #customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #4CAF50;
  color: white;
  }

    </style>
      <meta charset="utf-8">
    <title>Pizza Menu</title>
    <link rel="stylesheet" href="{% static "css/p0style.css" %}"/>
      <link rel="stylesheet" href="{% static "css/styling.css" %}"/>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  </head>
  <header class="head">
  <h1 style="text-align:center">Welcome to Pizza Mania</h1>
  <a href='http://127.0.0.1:8000'><button type="button" class="btn btn-dark" style="float: right;">Log Out</button></a>
</header>
  <body id="indexbody">
  <h2 style="text-align:center">Select the Menu you Wish and click on order now to enjoy the delecious Pizza :) :)</h2>
  <div class="djangotwo">
    {% if pizza_selection %}
      <table id="customers" align="center">
        <thead>
          <th>Sno.:</th>
          <th>Category:</th>
          <th>PizzaName:&nbsp;</th>
          <th>Size:</th>
          <th>Price:</th>
          <th>Topping:</th>
          <th>Tick to Checkout:</th>

        </thead>

      {% for acc in pizza_selection %}
      <tr>
          <td>&nbsp;&nbsp;{{acc.pid}}&nbsp;&nbsp;</td>
          <td>&nbsp;&nbsp;{{acc.catid}}&nbsp;&nbsp;</td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{acc.pname}}&nbsp;&nbsp;</td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;{{acc.psize}}&nbsp;&nbsp;</td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;{{acc.pprice}}&nbsp;&nbsp;</td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;{{acc.tname}}&nbsp;&nbsp;</td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" name= '{{ acc.pid }}'/></td>
        </tr>
      {% endfor %}
    </table>
      {% else %}
      <p> No Menu to display! Check your connection</p>
      {% endif %}
  </div>
  </body>
  <footer>
    <p id="finalval"></p>
    <a href = "{% url 'first_app:cart' %}" style="float:right"><button type="button" class="btn btn-outline-warning">Procced</button></a>
  </footer>
</html>
<!--<script>
  if(!localStorage.getItem('name'))
    localStorage.setItem('name',0);


    document.addEventListener('DOMContentLoader',() => {
      document.querySelector('#name').innerHTML = local.Storage.getItem('#name');

      document.querySelector('input').onclick = () => {
        localStorage.setItem(acc.pname,{{ acc.pname }});
        localStorage.setItem({{ acc.size }});
        localStorage.setItem({{ acc.pprice }});
        localStorage.setItem({{ acc.tname }});
      }
    })
</script>
-->

Project3:Pizza/templates/first_app/signup.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Pizza Mania</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
    	<link rel="stylesheet" href="../static/css/p0style.css">
      <link rel="stylesheet" href="../static/css/style.css">
    	<link rel="stylesheet" href="../static/css/styling.css">
    	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  </head>
<body id="indexbody">
      {% if registered %}
        <h1>Thank you for Registering!</h1>
      {% else %}
      <b><h1 class="container" style="text-align:center">Please Sign up here!</h1></b>
      <br><br>
      <form method="POST">
        {{ form.as_p }}
        <input type="submit" class = 'btn btn-primary' value="Submit">
      </form>
      {% endif %}
</body>
</html>

Project3:Pizza/templates/first_app/welcome.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Pizza Mania</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="../static/css/p0style.css">
    <link rel="stylesheet" href="../static/css/style.css">
    <link rel="stylesheet" href="../static/css/styling.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  </head>
  <header class="head">
  <h1 class="container">Welcome to Pizza Mania</h1>&nbsp; &nbsp; &nbsp;
  <a href='http://127.0.0.1:8000'><button type="button" class="btn btn-dark" style="float: right;">Log Out</button></a>
</header>
<body id="welcomebody">
  <br><br>
  <div id="welcome">
    <h2>Select any one Operation :)</h2>
    <ol>
      <!--<a href='http://127.0.0.1:8000/cart/'><li>View Cart and Payment</li></a>-->
      <a href="http://127.0.0.1:8000/menu/"><li>See Menu To Order :)</li></a>
    </ol>
  </div>
</body>
  <footer class="foot">
  	<h3 class="container">Get the code on Github:</h3>&nbsp;&nbsp;&nbsp;<a href="https://github.com/tshashankrock/CS50edx/tree/master/project0" target="_blank"><img  id="imgtag" src="../static/images/gitimg" alt="github" height="50" width="50"></a>
  </footer>
</html>